const filmType = {
    GET_FILM: 'GET_FILM',
    GET_FILM_SUCCESS: 'GET_FILM_SUCCESS',
    GET_SELECTED_FILM: 'GET_SELECTED_FILM',
    GET_LIST_FILMS: 'GET_LIST_FILMS',
    GET_LIST_FILMS_SUCCESS: 'GET_LIST_FILMS_SUCCESS',
    GET_POPULAR_FILMS: 'GET_POPULAR_FILMS',
    GET_POPULAR_FILMS_SUCCESS: 'GET_POPULAR_FILMS_SUCCESS',
}

export default filmType;